### ISSUE TITLE
`update()...execute()` should return an int

### ISSUE THREAD

**Issue by maxme** [yarolegovich/wellsql#1]
`SQLiteDatabase.update()` returns the number of rows affected, would be great to propagate it here: https://github.com/yarolegovich/wellsql/blob/9929d2d6b97e77d888e0a1f94368ad15e8dfd5a6/wellsql/src/main/java/com/yarolegovich/wellsql/UpdateQuery.java#L80-L86

So it could be used for things like that:
```
// update or insert
if (update()...execute() == 0) {
   insert();
}
```

**Comment by yarolegovich** [comment]
Hi, good idea. Will update on this weekends
